# Generated by Django 5.1.7 on 2025-09-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EU_Countries",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "EU_Countries",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EU_Parliament_Seats",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("seats", models.IntegerField()),
            ],
            options={
                "db_table": "EU_Parliament_Seats",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EU_Parties",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "EU_Parties",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("sector", models.CharField(max_length=100)),
                ("fake_news_technique", models.CharField(max_length=100)),
                ("counter_fake_news_technique", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="uploads/"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
