# Generated by Django 5.1.7 on 2025-09-12 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysimulator", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CounterDisinfoTechnique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="FakeNewsTechnique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="post",
            name="counter_fake_news_technique",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mysimulator.counterdisinfotechnique",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mysimulator.country"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="fake_news_technique",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mysimulator.fakenewstechnique",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="sector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mysimulator.sector"
            ),
        ),
    ]
